# Ocean View Resort - JDBC Configuration
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/oceanview
jdbc.username=postgres
jdbc.password=postgres

# Session
session.timeout.minutes=30


encryption.key=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
